### ISSUE TITLE
Unsupported processor

### ISSUE THREAD

**Issue by witchof0x20** [facebookexperimental/reverie#30]
I'm attempting to run the `noop` example, and get this error:
```
thread 'main' panicked at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/timer.rs:79:16:
Unsupported processor with feature info: FeatureInfo { extended_family_id: 0, extended_model_id: 9, family_id: 6, model_id: 154, stepping_id: 3, brand_index: 0, cflush_cache_line_size: 8, initial_local_apic_id: 8, max_logical_processor_ids: 128, edx_ecx: SSE3 | PCLMULQDQ | DTES64 | MONITOR | DSCPL | VMX | SMX | EIST | TM2 | SSSE3 | FMA | CMPXCHG16B | PDCM | PCID | SSE41 | SSE42 | X2APIC | MOVBE | POPCNT | TSC_DEADLINE | AESNI | XSAVE | OSXSAVE | AVX | F16C | RDRAND | FPU | VME | DE | PSE | TSC | MSR | PAE | MCE | CX8 | APIC | SEP | MTRR | PGE | MCA | CMOV | PAT | PSE36 | CLFSH | DS | ACPI | MMX | FXSR | SSE | SSE2 | SS | HTT | TM | PBE | 0x4800 }
 Full family_model: (6, 154)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7d3702e472b99be0f5de6608dd87af1df8f99428/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/7d3702e472b99be0f5de6608dd87af1df8f99428/library/core/src/panicking.rs:72:14
   2: reverie_ptrace::timer::get_rcb_perf_config
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/timer.rs:79:16
   3: reverie_ptrace::timer::TimerImpl::new
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/timer.rs:492:30
   4: reverie_ptrace::timer::Timer::new
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/timer.rs:170:22
   5: reverie_ptrace::task::TracedTask<L>::new
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/task.rs:376:20
   6: reverie_ptrace::tracer::postspawn::{{closure}}
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/tracer.rs:329:22
   7: reverie_ptrace::tracer::TracerBuilder<T>::spawn::{{closure}}
             at /home/user/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/8298a77/reverie-ptrace/src/tracer.rs:512:91
   8: intercept::main::{{closure}}
             at /home/user/src/github/foo/intercept/src/main.rs:26:10
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/runtime.rs:350:45
  18: intercept::main
             at /home/user/src/github/foo/intercept/src/main.rs:29:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/7d3702e472b99be0f5de6608dd87af1df8f99428/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Kernel: linux 6.5.13
Processor: 12th Gen Intel(R) Core(TM) i7-12700H

Any thoughts on the cause? 

Possibly similar: #13

**Comment by witchof0x20** [comment]
I applied a similar patch and things seem working (I don't quite know enough to ensure the timers / value stuff is correct)
```diff
diff --git a/reverie-ptrace/src/timer.rs b/reverie-ptrace/src/timer.rs
index 364f2de..52d53d0 100644
--- a/reverie-ptrace/src/timer.rs
+++ b/reverie-ptrace/src/timer.rs
@@ -69,6 +69,7 @@ pub(crate) fn get_rcb_perf_config() -> u64 {
         (0x06, 0x8E) | (0x06, 0x9E) => 0x5101c4,                // Intel Kabylake
         (0x06, 0xA5) | (0x06, 0xA6) => 0x5101c4,                // Intel Cometlake
         (0x06, 0x8D) => 0x5101c4, // Intel Alder Lake (e.g. i7-11800H laptop)
+        (0x06, 0x9A) => 0x5101c4, // Intel Alder Lake (e.g. i7-12700H laptop)
         (0x06, 0x8F) => 0x5101c4, // Intel Sapphire Rapids
         (0x06, 0x86) => 0x5101c4, // Intel Icelake
         (0x17, 0x8) => 0x5100d1,  // AMD Zen, Pinnacle Ridge
```
